name: batch_small_learning
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  cupertino_icons: ^1.0.8
  go_router: ^14.1.1

  authentication:
    path: packages/authentication

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  melos: ^6.2.0

flutter:

  uses-material-design: true


