name: authentication
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.2
  google_sign_in_ios: ^5.8.0

  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  shared_preferences: ^2.0.8
  freezed_annotation: ^2.2.0
  logger: ^2.4.0
  retrofit: ^4.4.1
  dio_smart_retry:
  dartz: ^0.10.1
  pretty_dio_logger:
  uuid: 4.5.1
  dart_scope_functions: ^1.0.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  freezed: ^2.3.5
  retrofit_generator: ^9.0.0

flutter:


